bind-addr: 0.0.0.0:8081
auth: password
password: qqqq

# This is the last step; set cert to none, complete all steps,
# then come back, set cert to true, and install the certification
cert: true
# Do not include the following line until cert is set to true
cert-host: codepi.local
